version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    image: voting:production
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $PROD_USERNAME
      POSTGRES_DB: $PROD_DATABASE
      POSTGRES_PASSWORD: $PROD_PASSWORD
volumes:
  pg-prod-data:
